### ISSUE TITLE
Supermicro X11SSH - add firmware building documentation

### ISSUE THREAD

**Issue by miczyg1** [Dasharo/dasharo-issues#328]
**Dasharo version (if applicable)**
v0.1.0

**Dasharo variant (if applicable)**
Dasharo compatible with Supermicro X11SSH

**Affected component(s) or functionality (if applicable)**
Documentation

**Brief summary**
Add firmware building documentation.

**Comment by pietrushnic** [comment]
Initial version of building documentation: https://github.com/Dasharo/dasharo-issues/issues/329

**Comment by pietrushnic** [comment]
- [ ] add information why compilation errors [like this](https://github.com/Dasharo/dasharo-issues/issues/329#issuecomment-1444647529) happen
- [ ] add clarification that warnings like [this](https://github.com/Dasharo/dasharo-issues/issues/329#issuecomment-1444701134) are nothing to worry about

**Comment by pietrushnic** [comment]
- [ ] add information on why compilation errors [like this](https://github.com/Dasharo/dasharo-issues/issues/329#issuecomment-1444647529) happen
- [ ] add clarification that warnings like [this](https://github.com/Dasharo/dasharo-issues/issues/329#issuecomment-1444701134) are nothing to worry about
