### ISSUE TITLE
NovaCustom NS5x/7x 12th Gen 06.11.2023 - Release v1.7.1 review

### ISSUE THREAD

**Issue by pietrushnic** [Dasharo/dasharo-issues#566]
### The problem you're addressing (if any)

Improvements of release deliverables.

### Describe the solution you'd like

- [ ] releases should be sent from one good, known email, e.g., Dasharo Release Team <releases@dasharo.com>, with the ability to reply to the whole release team. This issue can be resolved when we switch our process and newsletter configuration
- [ ] continues documentation improvements, e.g., [SOL](https://docs.dasharo.com/unified-test-documentation/dasharo-compatibility/347-sign-of-life/#sol002001-sol-string-shows-information-about-proprietary-ec) which was added in v1.7.1 links to test procedure, which may not show the value which we deliver through that feature, we should switch our strategy from test description focused to user documentation focused - to solve this issue we should present at any future release that we have zero pointers to documentation description, but rather focus on extending description of feature for the user and test documentation is in OSFV Robot Framework scripts (maybe even generated automatically to publicly accessible form)
- [ ] documentation versioning - it would quickly become a problem to have various versions of various features of Dasharo and document those. This is a separate topic on which we would have to focus on sooner or later.
- [ ] Dasharo Security options deserve an extensive section with each feature separated instead of bundled like [here](https://docs.dasharo.com/unified-test-documentation/dasharo-compatibility/347-sign-of-life/#sol002001-sol-string-shows-information-about-proprietary-ec)
- [ ] broken formatting of test steps in [31H](https://docs.dasharo.com/unified-test-documentation/dasharo-compatibility/31H-usb-type-c/#utc020001-usb-type-c-pd-current-limiting-ubuntu-2204)
- [ ] layout of [Dasharo menu documentation](https://docs.dasharo.com/dasharo-menu-docs/overview/) should be improved to accommodate changes - I don't understand why some features deserve their subpage and left-side menu items, and some are just sections in overview, this is not consistent
- [ ] `Setup menu password configuration` was not linked to [correct section](https://docs.dasharo.com/dasharo-menu-docs/overview/#user-password-management). It was linked to [menu guides](https://docs.dasharo.com/dasharo-menu-docs/overview/#dasharo-menu-guides)
- [ ] Mixed links `Better support for USB-PD power supplies` is linked to `Power delivery compatibility` issue as well as the other way around - maybe we can generate a fixed section based on correctly titled issues from github?
- [ ] Some issues were not closed despite being reported as fixed e.g. [suspend mode](https://github.com/Dasharo/dasharo-issues/issues/474) - ideally, we should have test results coupled with GitHub issues somehow, so when we have some passing test, it is linked to issue and another way around, I'm pretty sure this can be automated to avoid problems, then the bot would post "fixed for {dasharo_supported_hardware} in {release_version}"
- [ ] Some issues have had zero comments for more than a year, still open despite the fact that we claim those were fixed, e.g. [here](https://github.com/Dasharo/dasharo-issues/issues/474)
- [ ] Maybe it is worth releasing the RC version to those who are willing to test, e.g. [here](https://github.com/Dasharo/dasharo-issues/issues/295)
- [ ] Issues naming consistency e.g. `... (Windows 11)`, or `... on Windows 11`, or `in Ubuntu 22.04` etc.
- [ ] Openness score: why don't we show proprietary BIOS stats? https://docs.dasharo.com/variants/novacustom_ns5x_adl/openness-score/#cbfs-coreboot

### Where is the value to a user, and who might that user be?

Less confusion better consistency. Those improvements are needed not only fro users, but also for Dasharo Team.

**Comment by macpijan** [comment]
@pietrushnic  I created some dedicated issues for bigger tasks and fixed some links on your side.

**Comment by macpijan** [comment]
> we should switch our strategy from test description focused to user documentation focused - to solve this issue we should present at any future release that we have zero pointers to documentation description, but rather focus on extending description of feature for the user and test documentation is in OSFV Robot Framework scripts (maybe even generated automatically to publicly accessible form)

This is exactly what I have in mind. I would like to remove the manual documentation procedures entirely, and replace it with ones generated from OSFV. Partly that is why we do not invest in improvements of these a lot right now. But I agree, instead we could create feature documention.

**Comment by macpijan** [comment]
> Setup menu password configuration was not linked to [correct section](https://docs.dasharo.com/dasharo-menu-docs/overview/#user-password-management). It was linked to [menu guides](https://docs.dasharo.com/dasharo-menu-docs/overview/#dasharo-menu-guides)

It makes it more difficult to link, if it is not in the menu on the right side. I changed that some time ago, and it is changed back. I would need to see why.

**Comment by macpijan** [comment]
>  Issues naming consistency e.g. ... (Windows 11), or ... on Windows 11, or in Ubuntu 22.04 etc.

Any idea how to solve that? Issue naming guidelines?

**Comment by macpijan** [comment]
> Openness score: why don't we show proprietary BIOS stats? https://docs.dasharo.com/variants/novacustom_ns5x_adl/openness-score/#cbfs-coreboot

The only supported firmware on these NovaCustom devices is Dasharo.
We have not used proprietary firmware for the long time, I am not even sure which version we should use.
We do not have this automated to generate such a report for proprietary firmware right now.

**Comment by pietrushnic** [comment]
> Any idea how to solve that? Issue naming guidelines?

We have very little management activity regarding bug scrubbing and bug management. If we do not spend time on that activity, we don't learn. I don't think guidelines for bug submitters will work because if we want to use bug titles in release notes, we have to care about their quality, and quality checks/improvements can be done only by someone relatively experienced. We may have guidelines for our managers or experienced individual contributors. The key point to be aware of is that those bug titles will be in the release notes. Here we just lack consistency but sometimes we lack title quality. Let's be consistent when we report on what OS problems appear. Or maybe add labels.
